component: scf # (必选) 组件名称，在该实例中为scf
name: HiFiNi每日签到 # (必选) 组件实例名称。

#组件参数配置
inputs:
  name:
  namespace: default
  # 1. 默认写法，新建特定命名的 cos bucket 并上传
  src: code
  type: event # 函数类型，默认为 event(事件类型)，web(web类型)
  handler: com.lei2j.App::mainHandler #入口（函数类型为事件类型时生效）
  runtime: Java8 # 运行环境 默认 Nodejs10.15
  region: ap-shanghai # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 20 # 函数执行超时时间，单位秒
  initTimeout: 3 # 初始化超时时间，单位秒
  environment: #  环境变量
    variables: #  环境变量对象
      bbs_sid: 